<a href="https://colab.research.google.com/github/PIRomanCod/DataSciense_HW/blob/main/Hw1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [1]:
import numpy as np

vector = np.arange(1, 11, 1)
print("Вектор:")
print(vector)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення

In [ ]:
import numpy as np

matrix = np.zeros((3, 3), dtype=int)
print("Матриця:")
print(matrix)

Матриця:
[[0 0 0]
 [0 0 0]
 [0 0 0]]


3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.




In [ ]:
import numpy as np

# Встановлюємо насіння для генерації випадкових чисел, щоб отримати однакові результати кожного разу
np.random.seed(0)
matrix = np.random.randint(1, 11, size=(5, 5))
print("Матриця:")
print(matrix)

Матриця:
[[ 6  1  4  4  8]
 [10  4  6  3  5]
 [ 8  7  9  9  2]
 [ 7  8  8  9  2]
 [ 6 10  9 10  5]]


4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [ ]:
import numpy as np
np.random.seed(0)
matrix = np.random.random((4, 4))
print("Матриця:")
print(matrix)

Матриця:
[[0.5488135  0.71518937 0.60276338 0.54488318]
 [0.4236548  0.64589411 0.43758721 0.891773  ]
 [0.96366276 0.38344152 0.79172504 0.52889492]
 [0.56804456 0.92559664 0.07103606 0.0871293 ]]


5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [ ]:
import numpy as np
np.random.seed(0)
vector_1 = np.random.randint(1, 11, size=(5))
vector_2 = np.random.randint(1, 11, size=(5))
print("Вектор_1:")
print(vector_1)
print("\nВектор_2:")
print(vector_2)
print("\nСума векторів")
print(vector_1+vector_2)
print("\nРізниця векторів")
print(vector_1-vector_2)
print("\nМноження векторів")
print(vector_1*vector_2)

Вектор_1:
[6 1 4 4 8]

Вектор_2:
[10  4  6  3  5]

Сума векторів
[16  5 10  7 13]

Різниця векторів
[-4 -3 -2  1  3]

Множення векторів
[60  4 24 12 40]


6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [ ]:
import numpy as np
np.random.seed(0)
vector_1 = np.random.randint(1, 11, size=(7))
vector_2 = np.random.randint(1, 11, size=(7))
result = np.dot(vector_1, vector_2)
print("Вектор 1:")
print(vector_1)
print("\nВектор 2:")
print(vector_2)
print("\nСкалярний добуток векторів:")
print(result)

Вектор 1:
[ 6  1  4  4  8 10  4]

Вектор 2:
[6 3 5 8 7 9 9]

Скалярний добуток векторів:
273


7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [ ]:
import numpy as np
np.random.seed(0)
matrix_1 = np.array(np.random.randint(1, 11, size=(2, 2)))
matrix_2 = np.array(np.random.randint(1, 11, size=(2, 3)))
result = np.dot(matrix_1, matrix_2)
print("Матриця 1:")
print(matrix_1)
print("\nМатриця 2:")
print(matrix_2)
print("\nМноження матриць:")
print(result)

Матриця 1:
[[6 1]
 [4 4]]

Матриця 2:
[[ 8 10  4]
 [ 6  3  5]]

Множення матриць:
[[54 63 29]
 [56 52 36]]


8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

In [ ]:
import numpy as np

np.random.seed(0)
matrix = np.array(np.random.randint(1, 11, size=(3, 3)))
result = np.linalg.inv(matrix)

print("Матриця:")
print(matrix)
print("\nОбернена матриця:")
print(result)

Матриця:
[[ 6  1  4]
 [ 4  8 10]
 [ 4  6  3]]

Обернена матриця:
[[ 0.16363636 -0.09545455  0.1       ]
 [-0.12727273 -0.00909091  0.2       ]
 [ 0.03636364  0.14545455 -0.2       ]]


9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.


In [ ]:
import numpy as np
np.random.seed(0)
matrix = np.random.random((4, 4))
result = matrix.T

print("Матриця:")
print(matrix)
print("\nТранспонована матриця:")
print(result)

Матриця:
[[0.5488135  0.71518937 0.60276338 0.54488318]
 [0.4236548  0.64589411 0.43758721 0.891773  ]
 [0.96366276 0.38344152 0.79172504 0.52889492]
 [0.56804456 0.92559664 0.07103606 0.0871293 ]]

Транспонована матриця:
[[0.5488135  0.4236548  0.96366276 0.56804456]
 [0.71518937 0.64589411 0.38344152 0.92559664]
 [0.60276338 0.43758721 0.79172504 0.07103606]
 [0.54488318 0.891773   0.52889492 0.0871293 ]]


10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.


In [ ]:
import numpy as np

np.random.seed(0)

matrix = np.random.randint(1, 11, size=(3, 4))
vector = np.random.randint(1, 11, size=4)
result = np.dot(matrix, vector)

print("Матриця:")
print(matrix)
print("\nВектор:")
print(vector)
print("\nРезультат перемноження матриці на вектор:")
print(result)

Матриця:
[[ 6  1  4  4]
 [ 8 10  4  6]
 [ 3  5  8  7]]

Вектор:
[9 9 2 7]

Результат перемноження матриці на вектор:
[ 99 212 137]


11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [ ]:
import numpy as np

np.random.seed(0)

matrix = np.random.random((2, 3))
vector = np.random.random(3)
result = np.dot(matrix, vector)

print("Матриця:")
print(matrix)
print("\nВектор:")
print(vector)
print("\nРезультат перемноження матриці на вектор:")
print(result)

Матриця:
[[0.5488135  0.71518937 0.60276338]
 [0.54488318 0.4236548  0.64589411]]

Вектор:
[0.43758721 0.891773   0.96366276]

Результат перемноження матриці на вектор:
[1.45880096 1.23866193]


12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.



In [ ]:
import numpy as np

np.random.seed(0)

matrix_1 = np.random.randint(1, 11, size=(2, 2))
matrix_2 = np.random.randint(1, 11, size=(2, 2))
result = matrix_1 * matrix_2

print("Матриця_1:")
print(matrix_1)
print("\nМатриця_2:")
print(matrix_2)
print("\nРезультат поелементного перемноження матриць:")
print(result)

Матриця_1:
[[6 1]
 [4 4]]

Матриця_2:
[[ 8 10]
 [ 4  6]]

Результат поелементного перемноження матриць:
[[48 10]
 [16 24]]


13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.



In [ ]:
import numpy as np

np.random.seed(0)

matrix_1 = np.random.randint(1, 11, size=(2, 2))
matrix_2 = np.random.randint(1, 11, size=(2, 2))
result = np.dot(matrix_1, matrix_2)

print("Матриця_1:")
print(matrix_1)
print("\nМатриця_2:")
print(matrix_2)
print("\nДобуток матриць:")
print(result)

Матриця_1:
[[6 1]
 [4 4]]

Матриця_2:
[[ 8 10]
 [ 4  6]]

Добуток матриць:
[[52 66]
 [48 64]]


14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.



In [ ]:
import numpy as np

np.random.seed(0)

matrix = np.random.randint(1, 101, size=(5, 5))
print("Матриця:")
print(matrix)
result = np.sum(matrix)
print("\nСума елементів матриці:")
result

Матриця:
[[45 48 65 68 68]
 [10 84 22 37 88]
 [71 89 89 13 59]
 [66 40 88 47 89]
 [82 38 26 78 73]]

Сума елементів матриці:


1483

15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.



In [ ]:
import numpy as np

np.random.seed(0)

matrix_1 = np.random.randint(1, 11, size=(4, 4))
matrix_2 = np.random.randint(1, 11, size=(4, 4))
result = matrix_1 - matrix_2

print("Матриця_1:")
print(matrix_1)
print("\nМатриця_2:")
print(matrix_2)
print("\nРізниця матриць:")
print(result)

Матриця_1:
[[ 6  1  4  4]
 [ 8 10  4  6]
 [ 3  5  8  7]
 [ 9  9  2  7]]

Матриця_2:
[[ 8  8  9  2]
 [ 6 10  9 10]
 [ 5  4  1  4]
 [ 6  1  3  4]]

Різниця матриць:
[[-2 -7 -5  2]
 [ 2  0 -5 -4]
 [-2  1  7  3]
 [ 3  8 -1  3]]


16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.



In [ ]:
import numpy as np

np.random.seed(0)

matrix = np.random.random((3, 3))
result = np.sum(matrix, axis=1)

print("Матриця:")
print(matrix)

print(result)
vector = np.reshape(result, (3, 1))
print(vector)

Матриця:
[[0.5488135  0.71518937 0.60276338]
 [0.54488318 0.4236548  0.64589411]
 [0.43758721 0.891773   0.96366276]]
[1.86676625 1.6144321  2.29302297]
[[1.86676625]
 [1.6144321 ]
 [2.29302297]]


17. Створіть матрицю розміром 3x4 з довільними цілими числами і створіть матрицю з квадратами цих чисел.



In [ ]:
import numpy as np

matrix = np.random.randint(low=-10, high=10, size=(3, 4))
result = np.square(matrix)

print("Вихідна матриця:")
print(matrix)
print("\nМатриця з квадратами чисел:")
print(result)

Вихідна матриця:
[[ -5   5   5 -10]
 [  8  -7   7   9]
 [  9   9   4  -3]]

Матриця з квадратами чисел:
[[ 25  25  25 100]
 [ 64  49  49  81]
 [ 81  81  16   9]]


18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.



In [ ]:
import numpy as np

np.random.seed(0)
vector = np.random.randint(1, 51, size=4)
result = np.sqrt(vector)

print("Вихідний вектор:")
print(vector)
print("\nВектор з квадратними коренями чисел:")
print(result)

Вихідний вектор:
[45 48  1  4]

Вектор з квадратними коренями чисел:
[6.70820393 6.92820323 1.         2.        ]
